#!/usr/bin/env node
/* RadioRang build-time config generator.
 *
 * Writes public/rr-config.js from environment variables (Vercel injects its
 * project env vars into the build command, so this works on Vercel too), and
 * copies the compiled clock module into public/lib so static-only hosts can
 * serve it without the Node server's /lib mount.
 *
 * Environment variables (all optional — empty values = same origin):
 *   RR_API_BASE   — base URL of the realtime server's HTTP API (no trailing /)
 *                   e.g. https://rr-api.example.com
 *   RR_WS_BASE    — base URL for the WebSocket relay (ws:// or wss://)
 *                   e.g. wss://rr-api.example.com
 *   PUBLIC_ORIGIN — the public origin of THIS frontend, used for canonical
 *                   URLs and share links in metadata; falls back to the
 *                   browser's current origin at runtime when unset.
 *
 * Nothing here is secret — rr-config.js is served to every client on purpose.
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, '..');
const publicDir = path.join(root, 'public');

const config = {
  apiBase: (process.env.RR_API_BASE || '').replace(/\/+$/, ''),
  wsBase: (process.env.RR_WS_BASE || '').replace(/\/+$/, ''),
  origin: (process.env.PUBLIC_ORIGIN || '').replace(/\/+$/, ''),
};

const out = `/* Generated by scripts/gen-config.js at build time (from RR_API_BASE /
 * RR_WS_BASE / PUBLIC_ORIGIN). Committed default is empty = same origin.
 * Public configuration only — never contains secrets. */
window.RR_CONFIG = ${JSON.stringify(config, null, 2)};
`;
fs.writeFileSync(path.join(publicDir, 'rr-config.js'), out);
console.log('[gen-config] public/rr-config.js written:', JSON.stringify(config));

// Copy the compiled clock module into public/lib so static-only hosts
// (e.g. Vercel) can serve /lib/sync/clock.js without the Node server.
const src = path.join(root, 'dist', 'lib', 'sync', 'clock.js');
const destDir = path.join(publicDir, 'lib', 'sync');
if (fs.existsSync(src)) {
  fs.mkdirSync(destDir, { recursive: true });
  fs.copyFileSync(src, path.join(destDir, 'clock.js'));
  console.log('[gen-config] copied dist/lib/sync/clock.js -> public/lib/sync/clock.js');
} else {
  console.warn('[gen-config] WARNING: dist/lib/sync/clock.js not found — run the tsc step first (npm run build does both).');
}
